name: Deploy App

on: push

jobs:
  my-job:
    name: Deploy to surge
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to nullpointerexception.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'nullpointerexception.surge.sh'
          project: './build'
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
